
const bookData0 = [
    {
        name: 'Going Solo',
        id: 'goingSolo',
        link: 'ibooks://',
        author: 'Roald Dahl',
        coverType: 'jpg',
        progress: '46%',
        format: 'EBook',
    },
    {
        name: 'Faster Than Normal',
        id: 'faster',
        link: {
            audible: 'B0763VPQF6',
        },
        author: 'Peter Shankman',
        coverType: 'jpg',
        progress: '3h 0m left',
        format: 'AudioBook',
    },
]

const bookData1 = [
    {
        name: 'The Culture Map',
        id: 'cultureMap',
        link: 'ibooks://',
        author: 'Erin Meyer',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook',
    },
    {
        name: 'Brave New World',
        id: 'braveNewWorld',
        link: 'ibooks://',
        author: 'Aldous Huxley',
        coverType: 'jpg',
        progress: '22%',
        format: 'EBook',
    },
    {
        name: '12 Rules for Life',
        id: '12rules',
        link: 'ibooks://',
        author: 'Jordan B. Peterson',
        coverType: 'jpg',
        progress: '9%',
        format: 'EBook & Audiobook',
    },
    {
        name: 'The Ride of a Lifetime',
        id: 'ride',
        link: {
            audible: '0525499334',
        },
        author: 'Robert Iger',
        coverType: 'jpg',
        progress: '4h 39m left',
        format: 'AudioBook',
    },
    {
        name: 'The Martian',
        id: 'martian',
        link: {
            audible: 'B082BHJMFF',
        },
        author: 'Andy Weir',
        coverType: 'jpg',
        progress: '29%',
        format: 'EBook',
    },
    {
        name: 'Never Split the Difference',
        id: 'split',
        link: 'ibooks://',
        author: 'Chris Voss',
        coverType: 'jpg',
        progress: '4%',
        format: 'EBook',
    },
]
const bookData2 = [
    {
        name: 'The Four',
        id: 'four',
        link: 'ibooks://',
        author: 'Scott Galloway',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook & Audiobook',
    },
    {
        name: 'The Future is Asian',
        id: 'future',
        link: 'ibooks://',
        author: 'Parag Khanna',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook',
    },
    {
        name: 'The Raging 2020s',
        id: 'raging',
        link: 'ibooks://',
        author: 'Alec Ross',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook',
    },
    {
        name: 'The Expatriates',
        id: 'expats',
        link: 'ibooks://',
        author: 'Janice Y. K. Lee',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook',
    },
    {
        name: 'Gweilo: Memories of a Hong Kong Childhood',
        id: 'gweilo',
        link: 'ibooks://',
        author: 'Martin Booth',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook',
    },
    {
        name: 'The Culture Code',
        id: 'cultureCode',
        link: 'ibooks://',
        author: 'Daniel Coyle',
        coverType: 'jpg',
        progress: 'NEW',
        format: 'EBook',
    },
]

const bookData3 = [
    {
        name: 'No Rules Rules',
        id: 'noRules',
        link: 'ibooks://',
        author: 'Reed Hastings & Erin Meyer',
        coverType: 'jpg',
        progress: 'Finished',
        format: 'EBook',
    },
    {
        name: 'Homo Deus',
        id: 'homodeus',
        link: {
            audible: 'B01N4DCBK6',
        },
        author: 'Yuval Noah Harari',
        coverType: 'jpg',
        progress: 'FINISHED',
        format: 'AudioBook',
    },
    {
        name: 'Has the West Lost It?',
        id: 'west',
        link: 'ibooks://',
        author: 'Kishore Mahbubani',
        coverType: 'jpg',
        progress: 'FINISHED',
        format: 'EBook',
    },
    {
        name: 'Sapiens',
        id: 'sapiens',
        link: {
            audible: 'B0741G911Q',
        },
        author: 'Yuval Noah Harari',
        coverType: 'jpg',
        progress: 'FINISHED',
        format: 'AudioBook',
    },
    {
        name: "The Hitchhiker's Guide to the Galaxy",
        id: 'hitchhiker',
        link: {
            audible: 'B002VA9SWS',
        },
        author: 'Douglas Adams',
        coverType: 'jpg',
        progress: 'FINISHED',
        format: 'AudioBook',
    },
    {
        name: 'Boy',
        id: 'boy',
        link: 'ibooks://',
        author: 'Roald Dahl',
        coverType: 'jpg',
        progress: 'FINISHED',
        format: 'EBook',
    },
]

const bookData = [
    bookData0,
    bookData1,
    bookData2,
    bookData3,
]