
// {
//     name: 'Title',
//     id: 'identifier',
//     // link: {
//     //     netflix: '80197526'
//     // },
//     info: {
//         // service: 'service',
//         // studio: 'studio',
//         // location: 'location',
//         // date: '',
//         // weekday: '',
//         // desc: {
//         // //    seasons: 1,
//         // //    yearStart: 2021,
//         // //    yearEnd: null,
//         // //    genre: [
//         // //        'crime',
//         // //        'comedy',
//         // //    ],
//         // },
//         // summary: "summary",
//     },
//     style: {
//         // color: '000000',
//         // posterType: 'webp',
//         // titleType: 'png',
//         // titleSize: 'wide',
//     },
//     apps: {
//         // tvTimeID: 'identifier',
//         // reelgoodLink: 'link',
//         // imdbID: 'identifier',
//         // subReddit: 'subreddit',
//     },
// },
const movieData0 = [
    {
        name: 'Midnight Mass',
        id: 'midnight',
        link: {
            netflix: '81083626'
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Netflix',
            // date: '',
            // weekday: '',
            desc: {
               seasons: 1,
               yearStart: 2021,
               yearEnd: null,
               genre: [
                   'drama',
                   'horror',
               ],
            },
            summary: "The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.",
        },
        style: {
            color: '3c2e2c',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '367226',
            reelgoodLink: 'https://reelgood.com/show/midnight-mass',
            imdbID: 'tt10574558',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "Cowboy Bebop",
        id: "cowboy",
        link: "https://www.hulu.com/series/cowboy-bebop-af54be93-ee11-475c-b786-3543a9a7d4ba",
        info: {
            service: 'hulu',
            // studio: '',
            location: 'Hulu',
            desc: {
                seasons: 1,
                yearStart: 1998,
                yearEnd: 1999,
                genre: [
                    'animation',
                    'action',
                    'adventure',
                ],
            },
            summary: "The futuristic misadventures and tragedies of an easygoing bounty hunter and his partners.",
        },
        style: {
            color: '994d33',
            posterType: 'jpeg',
            titleType: 'png',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: "76885",
            reelgoodLink: "https://reelgood.com/show/cowboy-bebop-1998",
            imdbID: "tt0213338",
        },
    },
    {
        name: 'Archer',
        id: 'archer',
        link: 'https://www.hulu.com/series/archer-22b4b3c8-0827-42d2-a841-50e8f3464dc2',
        info: {
            service: 'hulu',
            studio: 'fx',
            location: 'Hulu',
            // date: '',
            // weekday: '',
            desc: {
               seasons: 12,
               yearStart: 2009,
               yearEnd: null,
               genre: [
                   'action',
                   'animation',
                   'crime',
               ],
            },
            summary: "Covert black ops and espionage take a back seat to zany personalities and relationships between secret agents and drones.",
        },
        style: {
            color: '337799',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '110381',
            reelgoodLink: 'https://reelgood.com/show/archer-2009',
            imdbID: 'tt1486217',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "Brooklyn Nine-Nine",
        id: "brooklyn",
        link: "https://www.hulu.com/series/brooklyn-nine-nine-daf48b7a-6cd7-4ef6-b639-a4811ec95232",
        info: {
            service: 'hulu',
            studio: 'nbc',
            location: 'Hulu',
            desc: {
                seasons: 8,
                yearStart: 2013,
                yearEnd: 2021,
                genre: [
                    'comedy',
                    'crime',
                ],
            },
            summary: "Detective Jake Peralta, a talented and carefree cop with the best arrest record, has never had to follow the rules too closely or work very hard. That changes when Ray Holt, a man with a lot to prove, becomes the new commanding officer of Brooklyn's 99th precinct. As Holt reminds Peralta to respect the badge, an extremely competitive colleague - Detective Amy Santiago - starts to close in on the hotshot cop's arrest record.",
        },
        style: {
            color: '8b6a4b',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "tall",
        },
        apps: {
            tvTimeID: "269586",
            reelgoodLink: "https://reelgood.com/show/brooklyn-nine-nine-2013",
            imdbID: "tt2467372",
        },
    },
]
const movieData1 = [
    {
        name: "Only Murders in the Building",
        id: "murders",
        link: "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
        info: {
            service: 'hulu',
            studio: 'hulu',
            location: 'Hulu',
            weekday: 'Tuesdays',
            desc: {
                seasons: 1,
                yearStart: 2021,
                yearEnd: null,
                genre: [
                    'crime',
                    'comedy',
                    'drama',
                ],
            },
            summary: "From the minds of Steve Martin, Dan Fogelman & John Hoffman comes a comedic murder-mystery series for the ages. Only Murders in the Building follows three strangers (Steve Martin, Martin Short, and Selena Gomez) who share an obsession with true crime and suddenly find themselves wrapped up in one. When a grisly death occurs inside their exclusive Upper West Side apartment building, the trio suspects murder and employs their precise knowledge of true crime to investigate the truth. As they record a podcast of their own to document the case, the three unravel the complex secrets of the building which stretch back years. Perhaps even more explosive are the lies they tell one another. Soon, the endangered trio comes to realize a killer might be living amongst them as they race to decipher the mounting clues before it’s too late.",
        },
        style: {
            color: '292A27',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: "399959",
            reelgoodLink: "https://reelgood.com/show/only-murders-in-the-building-2021",
            imdbID: "tt12851524",
            subReddit: 'OnlyMurdersHulu',
        },
    },
    {
        name: 'The Problem With Jon Stewart',
        id: 'problem',
        link: 'https://tv.apple.com/show/the-problem-with-jon-stewart/umc.cmc.4fcexvzqezr25p9weks6sxpob',
        info: {
            service: 'appleTV',
            studio: 'appleTV',
            location: ' TV+',
            // date: '',
            weekday: 'Thursdays',
            desc: {
               seasons: 1,
               yearStart: 2021,
               yearEnd: null,
               genre: [
                   'comedy',
                   'talk show',
               ],
            },
            summary: "It's easy to feel overwhelmed by the world's problems. It's harder to pinpoint the systems responsible for creating them. In this series, Jon Stewart brings together people impacted by different parts of a problem to discuss how we come up with change.",
        },
        style: {
            color: '334348',
            posterType: 'webp',
            titleType: 'webp',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '400756',
            reelgoodLink: 'https://reelgood.com/show/the-problem-with-jon-stewart-2021',
            imdbID: 'tt15084142',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Foundation',
        id: 'foundation',
        link: 'https://tv.apple.com/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3',
        info: {
            service: 'appleTV',
            studio: 'appleTV',
            location: ' TV+',
            weekday: 'Fridays',
            desc: {
                seasons: 1,
                yearStart: 2021,
                yearEnd: null,
                genre: [
                    'drama',
                    'sci-fi',
                ],
            },
            summary: "Dr. Hari Seldon and his loyal followers attempt to preserve their culture as the galaxy collapses.",
        },
        style: {
            color: '70655B',
            posterType: 'webp',
            titleType: 'webp',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '366972',
            reelgoodLink: 'https://reelgood.com/show/foundation-2020',
            imdbID: 'tt0804484',
            subReddit: 'FoundationTV',
        },
    },
    {
        name: "Ted Lasso",
        id: "ted",
        link: null,
        info: {
            service: 'appleTV',
            studio: 'appleTV',
            location: "Apple TV+",
            weekday: 'Fridays',
            desc: {
                seasons: 2,
                yearStart: 2020,
                yearEnd: null,
                genre: [
                    'comedy',
                    'drama',
                    'sport',
                ],
            },
            summary: "Ted Lasso, an American football coach, moves to England when he’s hired to manage a soccer team—despite having no experience. With cynical players and a doubtful town, will he get them to see the Ted Lasso Way?",
        },
        style: {
            color: '35465e',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "383203",
            reelgoodLink: "https://reelgood.com/show/ted-lasso-2020",
            imdbID: "tt10986410",
            subReddit: "TedLasso",
        },
    },
    {
        name: "What We Do in the Shadows",
        id: "shadows",
        link: "https://www.hulu.com/series/what-we-do-in-the-shadows-0b10c46a-12f0-4357-8a00-547057b49bac",
        info: {
            service: 'hulu',
            studio: 'fx',
            location: 'Hulu',
            weekday: 'Fridays',
            desc: {
                seasons: 3,
                yearStart: 2019,
                yearEnd: null,
                genre: [
                    'Comedy',
                    'Drama',
                    'Fantasy',
                ],
            },
            summary: "Three vampires, Nandor, Colin Robinson and Nadja, struggle to keep up with the duties and responsibilities of everyday life as they reside in an apartment in New York.",
        },
        style: {
            color: '1C2C70',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: "358211",
            reelgoodLink: "https://reelgood.com/show/what-we-do-in-the-shadows-2019",
            imdbID: "tt7908628",
            subReddit: 'WhatWeDointheShadows',
        },
    },
    {
        name: 'Family Guy',
        id: 'family',
        link: 'https://www.hulu.com/series/family-guy-3c3c0f8b-7366-4d15-88ab-18050285978e',
        info: {
            service: 'hulu',
            studio: 'fox',
            location: 'Hulu',
            // date: '',
            weekday: 'Sundays',
            desc: {
               seasons: 20,
               yearStart: 1999,
               yearEnd: null,
               genre: [
                   'animation',
                   'comedy',
               ],
            },
            summary: "Peter Griffin and his family of two teenagers, a smart dog, a devilish baby and his wife find themselves in some of the most hilarious scenarios.",
        },
        style: {
            color: '0B6F38',
            posterType: 'webp',
            titleType: 'svg',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: '75978',
            reelgoodLink: 'https://reelgood.com/show/family-guy-1999',
            imdbID: 'tt0182576',
            // subReddit: 'subreddit',
        },
    },
]
const movieData2 = [
    {
        name: 'South Park',
        id: 'southpark',
        // link: {
        //     netflix: '80197526'
        // },
        info: {
            // service: 'service',
            // studio: 'studio',
            location: 'Downloaded',
            // date: '',
            // weekday: '',
            desc: {
               seasons: 24,
               yearStart: 1997,
               yearEnd: null,
               genre: [
                   'animation',
                   'comedy',
               ],
            },
            summary: "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.",
        },
        style: {
            color: 'b8c2c0',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '75897',
            reelgoodLink: 'https://reelgood.com/show/south-park-1997',
            imdbID: 'tt0121955',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'The Simpsons',
        id: 'simpsons',
        link: 'https://www.hulu.com/series/the-simpsons-47332072-d7fb-48b3-a5f7-ca8c6915ca27',
        info: {
            service: 'hulu',
            studio: 'fox',
            location: 'Hulu',
            // date: '',
            // weekday: '',
            desc: {
               seasons: 33,
               yearStart: 1989,
               yearEnd: 2021,
               genre: [
                   'animation',
                   'comedy',
               ],
            },
            summary: "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie.",
        },
        style: {
            color: '685467',
            posterType: 'webp',
            titleType: 'svg',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/show/the-simpsons-1989',
            imdbID: 'tt0096697',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Superstore',
        id: 'superstore',
        link: 'https://www.hulu.com/series/superstore-727810b8-e54b-4f01-9381-a79ab5661bf7',
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: 'Comedy &#149 6 Seasons &#149 2015 - 2021',
            summary: "Revolving around a group of employees at a big-box store, it examines love, friendship and the beauty of everyday moments.",
        },
        style: {
            color: '0070DB',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '295648',
            reelgoodLink: 'https://reelgood.com/show/superstore-2015',
            imdbID: 'tt4477976',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "What If?",
        id: "whatif",
        link: "https://www.disneyplus.com/series/what-if/7672ZVj1ZxU9",
        info: {
            service: '',
            studio: '',
            location: "Disney+",
            description: "Action &#149 Adventure &#149 Animation &#149 1 Season &#149 2021 - Present",
            summary: "Taking inspiration from the comic books of the same name, each episode explores a pivotal moment from the Marvel Cinematic Universe and turns it on its head, leading the audience into uncharted territory.",
        },
        style: {
            color: '0F0F38',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: "367147",
            reelgoodLink: "https://reelgood.com/show/what-if-2021",
            imdbID: "tt10168312",
            subReddit: 'MarvelsWhatIf',
        },
    },
    {
        name: "Sex Education",
        id: "edu",
        link: {
            netflix: '80197526'
        },
        info: {
            service: 'netflix',
            studio: '',
            location: "Netflix",
            description: "Comedy &#149 Teen &#149 3 Seasons &#149 2019 - Present",
            summary: "Insecure Otis has all the answers when it comes to sex advice, thanks to his therapist mom. So rebel Maeve proposes a school sex-therapy clinic.",
        },
        style: {
            color: '6d6256',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "356317",
            reelgoodLink: "https://reelgood.com/show/sex-education-2019",
            imdbID: "tt7767422",
            subReddit: "NetflixSexEducation",
        },
    },
    {
        name: "Jojo's Bizzare Adventures",
        id: "jojo",
        link: {
            netflix: '80179831'
        },
        info: {
            service: 'netflix',
            studio: '',
            location: "Netflix",
            description: "Animation &#149 Action &#149 Adventure &#149 4 Seasons &#149 2012 - Present",
            summary: "Jonathan Joestar, nicknamed JoJo, becomes involved in a battle against his stepbrother, Dio Brando, who is intent on taking control of the Joestar fortune. To do this, Dio uses the power of an ancient stone mask, which allows him to become a powerful vampire. The hybrid anime series takes pieces from such genres as paranormal, adventure, comedy, action and fantasy.",
        },
        style: {
            color: '2C2850',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "tall",
        },
        apps: {
            tvTimeID: "262954",
            // tvTimeRate: "9.74",
            reelgoodLink: "https://reelgood.com/show/jojos-bizarre-adventure-2012",
            // reelgoodRate: "72",
            imdbID: "tt2359704",
            // imdbRate: "8.4",
        },
    },
    {
        name: "Money Heist",
        id: "money",
        link: {
            netflix: '80192098'
        },
        info: {
            service: 'netflix',
            studio: '',
            location: "Netflix",
            description: "Action &#149 Crime &#149 Mystery &#149 3 Seasons &#149 2017 - Present",
            summary: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
        },
        style: {
            color: '3f1513',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "327417",
            reelgoodLink: "https://reelgood.com/show/money-heist-2017",
            imdbID: "tt6468322",
        },
    },
    {
        name: 'Narcos: Mexico',
        id: 'narcos',
        link: 'https://www.netflix.com/title/80997085',
        info: {
            service: 'netflix',
            studio: '',
            location: 'Netflix',
            description: 'Crime &#149 Drama &#149 3 Seasons &#149 2018 - Present',
            summary: "This continuation of 'Narcos' explores the origins of the modern drug war by going back to its roots, starting at a time when the Mexican trafficking world was a loose, disorganized confederation of independent growers and dealers. It's the 1980s, and Felix Gallardo takes the helm of the Guadalajara Cartel, unifying traffickers to build an empire. As DEA agent Kiki Camarena moves his wife and young son from California to Guadalajara to take on a new post, he learns his assignment is more challenging than he imagined. A tragic chain of events unfolds as Camarena gains intelligence on Gallardo and becomes more entangled in the mission.",
        },
        style: {
            color: '5980C4',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: '353232',
            reelgoodLink: 'https://reelgood.com/show/narcos-mexico-2018',
            imdbID: 'tt8714904',
            // subReddit: null,
        },
    },
    {
        name: "Dave",
        id: "dave",
        link: "https://www.hulu.com/series/dave-ac3a96f0-9614-46af-b524-f59c7d281946",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Comedy &#149 Music &#149 2 Seasons &#149 2020 - Present",
            summary: "Dave centers on a neurotic man in his late 20s who has convinced himself that he is destined to be one of the best rappers of all time. Now he must convince his closest friends, because with their help, he actually might convince the world. Simultaneously exasperating and inspiring to his friends, he vows to leave no stone unturned on his quest to become the next superstar.",
        },
        style: {
            color: '889898',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: "354905",
            reelgoodLink: "https://reelgood.com/show/dave-2020",
            imdbID: "tt8531222",
        },
    },
    {
        name: "Love Death Robots",
        id: "ldr",
        link: 'https://www.netflix.com/title/80174608',
        info: {
            service: 'netflix',
            studio: '',
            location: "Netflix",
            description: "Animation &#149 Sci-Fi &#149 2 Seasons &#149 2019 - Present",
            summary: "This collection of animated short stories spans several genres, including science fiction, fantasy, horror and comedy. World-class animation creators bring captivating stories to life in the form of a unique and visceral viewing experience. The animated anthology series includes tales that explore alternate histories, life for robots in a post-apocalyptic city and a plot for world domination by super-intelligent yogurt. Among the show's executive producers is Oscar-nominated director David Fincher.",
        },
        style: {
            color: '200f17',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "357888",
            reelgoodLink: "https://reelgood.com/show/love-death-robots-2019",
            imdbID: "tt9561862",
            subReddit: "LoveDeathAndRobots",
        },
    },
]
const movieData3 = [
    {
        name: 'Eternals',
        id: 'eternals',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            description: 'Action &#149 Adventure &#149 Drama &#149 2021',
            summary: "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
        },
        style: {
            color: '645542',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/movie/eternals-2021',
            imdbID: 'tt9032400',
            // subReddit: null,
        },
    },
    {
        name: "Ghost in the Shell",
        id: "ghost",
        link: {
            primeVideo: 'B07WQZDXTM',
        },
        info: {
            service: '',
            studio: '',
            location: "Prime Video",
            description: "Animation &#149 Action &#149 Crime &#149 1995",
            summary: "In the year 2029, the barriers of our world have been broken down by the net and by cybernetics, but this brings new vulnerability to humans in the form of brain-hacking. When a highly-wanted hacker known as The Puppetmaster begins involving them in politics, Section 9, a group of cybernetically enhanced cops, are called in to investigate and stop the Puppetmaster.",
        },
        style: {
            color: '313C82',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: null,
            reelgoodLink: "https://reelgood.com/movie/ghost-in-the-shell-1995",
            imdbID: "tt0113568",
        },
    },
    {
        name: "Your Name.",
        id: "yourname",
        link: null,
        info: {
            service: '',
            studio: '',
            location: "Download",
            description: "Animation &#149 Drama &#149 Fantasy &#149 2016",
            summary: "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
        },
        style: {
            color: '768a8e',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: null,
            reelgoodLink: "https://reelgood.com/movie/your-name-2016",
            imdbID: "tt5311514",
        },
    },
    {
        name: "Free Guy",
        id: "free",
        link: null,
        info: {
            service: '',
            studio: '',
            location: "Coming Soon",
            description: "Adventure &#149 Comedy &#149 Sci-Fi &#149 2021",
            summary: "When a bank teller discovers he is actually a background player in an open-world video game, he decides to become the hero of his own story -- one that he can rewrite himself. In a world where there are no limits, he is determined to save the day his way before it is too late, and maybe find a little romance with the coder who conceived him.",
        },
        style: {
            color: '599DAA',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: null,
            reelgoodLink: "https://reelgood.com/movie/free-guy-2020",
            imdbID: "tt6264654",
        },
    },
    {
        name: 'Knives Out',
        id: 'knives',
        link: {
            primeVideo: 'B081W68DP2'
        },
        info: {
            service: 'prime',
            // studio: 'studio',
            location: 'Prime Video',
            description: 'Comedy &#149 Crime &#149 Drama &#149 2019',
            summary: "A detective investigates the death of a patriarch of an eccentric, combative family.",
        },
        style: {
            color: '3d250f',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/movie/knives-out-2019',
            imdbID: 'tt8946378',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Being John Malkovich',
        id: 'john',
        // link: {
        //     netflix: '80197526'
        // },
        info: {
            // service: 'service',
            // studio: 'studio',
            location: 'Download',
            description: 'Comedy &#149 Drama &#149 Fantasy &#149 1999',
            summary: "A puppeteer discovers a portal that leads literally into the head of movie star John Malkovich.",
        },
        style: {
            color: '6c4e44',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/movie/being-john-malkovich-1999',
            imdbID: 'tt0120601',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'The Year the Earth Changed',
        id: 'earth',
        link: 'https://tv.apple.com/movie/the-year-earth-changed/umc.cmc.3fob3t7nfhehpb3ilgynzxmnu',
        info: {
            service: 'appleTV',
            studio: 'appleTV',
            location: ' TV+',
            description: 'Documentary &#149 Nature &#149 2021',
            summary: "Narrated by David Attenborough, never-before-seen footage shows how our living in lockdown opened the door for nature to bounce back and thrive. Across the seas, skies, and lands, Earth found its rhythm when we came to a stop.",
        },
        style: {
            color: '484b51',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/movie/the-year-earth-changed-2021',
            imdbID: 'tt14372240',
            // subReddit: 'subreddit',
        },
    },
]
const movieData4 = [
    {
        name: 'The Witcher',
        id: 'witcher',
        link: {
            netflix: '80189685'
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Netflix',
            // date: '',
            // weekday: '',
            desc: {
               seasons: 1,
               yearStart: 2019,
               yearEnd: null,
               genre: [
                   'action',
                   'adventure',
                   'fantasy',
               ],
            },
            summary: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
        },
        style: {
            color: '515d63',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/show/the-witcher-2020',
            imdbID: 'tt5180504',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Vikings',
        id: 'vikings',
        link: 'https://www.hulu.com/series/vikings-8bc072a3-4a5e-47cb-9cb6-bc3dc3785fe1',
        info: {
            service: 'hulu',
            // studio: 'studio',
            location: 'Hulu',
            // date: '',
            // weekday: '',
            desc: {
               seasons: 6,
               yearStart: 2013,
               yearEnd: 2021,
               genre: [
                   'action',
                   'adventure',
                   'history',
               ],
            },
            summary: "Ragnar is pitted against Rollo over a land dispute he's trying to settle on behalf of King Horik. A deadly fever hits Kattegat putting Ragnar's wife and daughter's lives in grave danger.",
        },
        style: {
            color: '4f6368',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/show/vikings-2013',
            imdbID: 'tt2306299',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Dear White People',
        id: 'dear',
        link: {
            netflix: '80095698'
        },
        info: {
            service: 'netflix',
            studio: '',
            location: 'Netflix',
            description: 'Comedy &#149 Drama &#149 4 Seasons &#149 2017 - 2021',
            summary: "Students of color navigate the daily slights and slippery politics of life at an Ivy League college that's not nearly as \"post-racial\" as it thinks.",
        },
        style: {
            color: '813a2a',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'tall',
        },
        apps: {
            // tvTimeID: 'identifier',
            reelgoodLink: 'https://reelgood.com/show/dear-white-people-2017',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'For All Mankind',
        id: 'mankind',
        link: 'https://tv.apple.com/show/for-all-mankind/umc.cmc.6wsi780sz5tdbqcf11k76mkp7',
        info: {
            service: '',
            studio: '',
            location: ' TV+',
            description: 'Sci-Fi &#149 2 Seasons &#149 2019 - Present',
            summary: "Exploring the possibilities that might exist if the global space race had continued and where humanity would be now.",
        },
        style: {
            color: '3e587a',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '356202',
            reelgoodLink: 'https://reelgood.com/show/for-all-mankind-2019',
            imdbID: 'tt7772588',
            // subReddit: null,
        },
    },
    {
        name: 'Dark',
        id: 'dark',
        link: 'https://www.netflix.com/title/80100172',
        info: {
            service: 'netflix',
            studio: '',
            location: 'Netflix',
            description: 'Crime &#149 Drama &#149 Mystery &#149 3 Seasons &#149 2017 - 2020',
            summary: "When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids. The mystery-drama series introduces an intricate puzzle filled with twists that includes a web of curious characters, all of whom have a connection to the town's troubled history -- whether they know it or not. The story includes supernatural elements that tie back to the same town in 1986. 'Dark' represents the first German original series produced for Netflix.",
        },
        style: {
            color: '3f3a2d',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '334824',
            reelgoodLink: 'https://reelgood.com/show/dark-2017',
            imdbID: 'tt5753856',
            // subReddit: null,
        },
    },
    {
        name: 'Fringe',
        id: 'fringe',
        link: {
            primeVideo: 'B001FVV2X2',
        },
        info: {
            service: '',
            studio: '',
            location: 'Prime Video',
            description: 'Drama &#149 Mystery &#149 Sci-Fi &#149 5 Seasons &#149 2008 - 2013',
            summary: "FBI Special Agent Olivia Dunham is assigned to the bureau's Fringe Division, in which she investigates unusual crimes and occurrences. Assisting Olivia in her investigations are once-institutionalised scientist Dr Walter Bishop, his jack-of-all-trades son, Peter, and FBI Junior Agent Astrid Farnsworth. As the team investigates cases of science gone awry, they discover connections to their own past and to a parallel universe. As the team explores life and solves cases in these interconnected worlds, new discoveries and complications continue to arise.",
        },
        style: {
            color: '7a726b',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: '82066',
            reelgoodLink: null,
            imdbID: 'tt1119644',
            subReddit: null,
        },
    },
    {
        name: "Y: The Last Man",
        id: "lastman",
        link: "https://www.hulu.com/series/y-the-last-man-9fb2d79b-1280-48be-b185-f989b9c9519a",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: 'Action &#149 Adventure &#149 Drama &#149 1 Season &#149 2021 - Present',
            summary: 'A drama based on DC Comics\' acclaimed series by Brian K. Vaughan and Pia Guerra, Y: The Last Man traverses a post-apocalyptic world in which a cataclysmic event decimates every mammal with a Y chromosome but for one cisgender man and his pet monkey. The series follows the survivors in this new world as they struggle with their efforts to restore what was lost and the opportunity to build something better.',
        },
        style: {
            color: '5D080D',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: "399959",
            reelgoodLink: 'https://reelgood.com/show/y-the-last-man-2021',
            imdbID: "tt8042500",
            subReddit: 'YTheLastMan',
        },
    },
    {
        name: 'The Spy',
        id: 'spy',
        link: {
            netflix: '80178151'
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Netflix',
            description: 'Drama &#149 1 Season &#149 2019',
            summary: "In the 1960s, Israeli clerk-turned-secret agent Eli Cohen goes deep undercover inside Syria on a perilous, years-long mission to spy for Mossad.",
        },
        style: {
            color: '7f6b57',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: '368109',
            reelgoodLink: 'https://reelgood.com/show/the-spy-2019',
            imdbID: 'tt5952634',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Chernobyl',
        id: 'chernobyl',
        // link: {
        //     netflix: '80197526'
        // },
        info: {
            service: 'hbo',
            // studio: '',
            location: 'HBO Max',
            description: 'History &#149 Thriller &#149 1 Season &#149 2019',
            summary: "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
        },
        style: {
            color: '86a097',
            posterType: 'jpg',
            titleType: 'svg',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '360893',
            reelgoodLink: 'https://reelgood.com/show/chernobyl-2019',
            imdbID: 'tt7366338',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "Line of Duty",
        id: "lineofduty",
        link: "https://www.hulu.com/series/line-of-duty-0efc0f95-c575-46da-b28f-a30a13d86b37",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Thriller &#149 6 Season &#149 2012 - Present",
            summary: "After refusing to help cover up an unlawful and fatal shooting by members of his team, Detective Sergeant Steve Arnott is transferred to Anti-Corruption Unit 12, AC-12. Run by zealous Superintendent Ted Hastings, the department is responsible for investigating possible corruption within the Central Police force. Working alongside DS Arnott is Detective Inspector Kate Fleming, who is an undercover specialist. With the help and oversight of Hastings, Arnott and Fleming take on difficult cases, which lead from laddering to mishandling evidence.",
        },
        style: {
            color: '262841',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: '260092',
            reelgoodLink: "https://reelgood.com/show/line-of-duty-2012",
            imdbID: "tt2303687",
        },
    },
    {
        name: 'Mindhunter',
        id: 'mindhunter',
        link: {
            netflix: '80114855'
        },
        info: {
            service: 'netflix',
            // studio: 'studio',
            location: 'Netflix',
            description: 'Crime &#149 Drama &#149 Thriller &#149 2 Seasons &#149 2017 - 2019',
            summary: "In the late 1970s two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.",
        },
        style: {
            color: '838383',
            posterType: 'webp',
            titleType: 'svg',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '328708',
            reelgoodLink: 'https://reelgood.com/show/mindhunter-2017',
            imdbID: 'tt5290382',
            // subReddit: 'subreddit',
        },
    },
]
const movieData5 = [
    {
        name: "Twin Peaks",
        id: "twinpeaks",
        // link: "https://watch.amazon.com/detail?asin=B08QM4K1K5",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            // description: "Cars &#149 Comedy &#149 Travel &#149 4 Seasons &#149 2016 - Present",
            // summary: "Confined to the United Kingdom by COVID-19, the hosts embark on a quest to find out why American cars from the 1970s never took off in Britain; they travel around Scotland in a Cadillac Coupe de Ville, a Lincoln Continental and a Buick Riviera.",
        },
        style: {
            color: '300',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: "tall",
        },
    },
    {
        name: 'Curb Your Enthusiasm',
        id: 'curb',
        link: 'https://play.hbomax.com/page/urn:hbo:page:GVU2bygQ1go7DwvwIAT3r:type:series',
        info: {
            service: '',
            studio: '',
            location: 'HBO Max',
            description: 'Comedy &#149 10 Seasons &#149 2000 - Present',
            // summary: "summary",
        },
        style: {
            color: '746e6e',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '76203',
            reelgoodLink: 'https://reelgood.com/show/curb-your-enthusiasm-2000',
            imdbID: 'tt0264235',
            // subReddit: null,
        },
    },
    {
        name: "Legion",
        id: "legion",
        link: "https://www.hulu.com/series/legion-ae87e56c-5b3b-44f6-9154-b07c8e60fe6c",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Sci-Fi &#149 3 Seasons &#149 2017 - 2019",
            summary: "David Haller, AKA Legion, is a troubled young man who may be more than human. Diagnosed as schizophrenic, David has been in and out of psychiatric hospitals for years. But after a strange encounter with a fellow patient, he's confronted with the possibility that the voices he hears and the visions he sees might be real.",
        },
        style: {
            color: '862849',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "320724",
            // reelgoodLink: "https://www.hulu.com/series/legion-ae87e56c-5b3b-44f6-9154-b07c8e60fe6c",
            imdbID: "tt5114356",
        },
    },
    {
        name: "Formula 1: Drive to Survive",
        id: "drive",
        // link: "https://watch.amazon.com/detail?asin=B08QM4K1K5",
        info: {
            service: 'netflix',
            studio: '',
            location: "Netflix",
            // description: "Cars &#149 Comedy &#149 Travel &#149 4 Seasons &#149 2016 - Present",
            // summary: "Confined to the United Kingdom by COVID-19, the hosts embark on a quest to find out why American cars from the 1970s never took off in Britain; they travel around Scotland in a Cadillac Coupe de Ville, a Lincoln Continental and a Buick Riviera.",
        },
        style: {
            color: '4d5372',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
    },
    {
        name: "The Grand Tour",
        id: "grandTour",
        link: {
            primeVideo: 'B08QM4K1K5',
        },
        info: {
            service: '',
            studio: '',
            location: "Prime Video",
            description: "Cars &#149 Comedy &#149 Travel &#149 4 Seasons &#149 2016 - Present",
            summary: "Confined to the United Kingdom by COVID-19, the hosts embark on a quest to find out why American cars from the 1970s never took off in Britain; they travel around Scotland in a Cadillac Coupe de Ville, a Lincoln Continental and a Buick Riviera.",
        },
        style: {
            color: 'C05D38',
            posterType: 'webp',
            titleType: 'svg',
            titleSize: "mid",
        },
        apps: {
            tvTimeID: "314087",
            // tvTimeRate: "8.82",
            reelgoodLink: "https://reelgood.com/show/the-grand-tour-2016",
            // reelgoodRate: "83",
            imdbID: "tt5712554",
            // imdbRate: "8.7",
        },
    },
    {
        name: "Futurama",
        id: "futurama",
        link: "https://www.hulu.com/series/futurama-85bf4cc1-cd8b-4469-ad87-7289217a0b74",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Animation &#149 Comedy &#149 Sci-Fi &#149 8 Seasons &#149 1999 - 2013",
            summary: "Accidentally frozen, pizza-deliverer Fry wakes up 1,000 years in the future. He is taken in by his sole descendant, an elderly and addled scientist who owns a small cargo delivery location. Among the other crew members are Capt. Leela, accountant Hermes, intern Amy, obnoxious robot Bender and lobsterlike moocher Dr. Zoidberg.",
        },
        style: {
            color: 'E25924',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "314087",
            reelgoodLink: "https://reelgood.com/show/futurama-1999",
            // imdbID: "tt5712554",
        },
    },
]
const movieData6 = [
    {
        name: 'Fairfax',
        id: 'fairfax',
        // link: 'watchlink',
        info: {
            service: 'prime',
            studio: 'prime',
            location: 'Prime Video',
            date: 'Oct 29, 2021',
            description: 'Animation &#149 Comedy &#149 1 Season &#149 2021 - Present',
            summary: "Animated series centering on four middle school friends on their quest for fame on L.A.'s Fairfax Avenue.",
        },
        style: {
            color: '0B6F38',
            posterType: 'jpg',
            // titleType: 'png',
            // titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            imdbID: 'tt7492014',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Cowboy Bebop',
        id: 'cowboy2',
        link: {
            netflix: '80207033',
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Netflix',
            date: 'Nov 19, 2021',
            description: 'Action &#149 Adventure &#149 Crime &#149 1 Season &#149 2021 - Present',
            summary: "A ragtag crew of bounty hunters chases down the galaxy's most dangerous criminals. They'll save the world ... for the right price. A live-action series.",
        },
        style: {
            color: '66472A',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: '367234',
            reelgoodLink: 'https://reelgood.com/show/cowboy-bebop-2021',
            imdbID: 'tt1267295',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "The Mandalorian",
        id: "mando",
        link: null,
        info: {
            service: 'disney',
            studio: 'disney',
            location: 'Disney+',
            date: 'Dec 24, 2021',
            description: 'Action &#149 Adventure &#149 Sci-Fi &#149 2 Seasons &#149 2019 - Present',
            summary: "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
        },
        style: {
            color: '4d627f',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: "361753",
            reelgoodLink: "https://reelgood.com/show/the-mandalorian-2019",
            imdbID: 'tt8111088',
            subReddit: 'TheMandalorianTV',
        },
    },
    {
        name: "Billions",
        id: "billions",
        link: null,
        info: {
            service: '',
            studio: 'showtime',
            location: "Showtime",
            date: 'Jan 23, 2022',
            desc: {
                seasons: 5,
                yearStart: 2016,
                yearEnd: null,
                genre: [
                    'drama',
                    'money',
                ],
            },
            summary: "Wealth, influence and corruption collide in this drama set in New York. Shrewd U.S. Attorney Chuck Rhoades is embroiled in a high-stakes game of predator vs. prey with Bobby Axelrod, an ambitious hedge-fund king. To date, Rhoades has never lost an insider trading case -- he's 81-0 -- but when criminal evidence turns up against Axelrod, he proceeds cautiously in building the case against Axelrod, who employs Rhoades' wife, psychiatrist Wendy, as a performance coach for his company.",
        },
        style: {
            color: '6f4c2d',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "279536",
            reelgoodLink: "https://reelgood.com/show/billions-2016",
            imdbID: "tt4270492",
            subReddit: 'Billions'
        },
    },
]
const movieData7 = [
    {
        name: 'Alice in Borderland',
        id: 'alice',
        link: {
            netflix: '80200575'
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Coming Soon',
            // date: '',
            // weekday: '',
            // desc: {
            //     seasons: 2,
            //     yearStart: 2020,
            //     yearEnd: null,
            //     genre: [
            //         'crime',
            //         'comedy',
            //     ],
            // },
            // summary: "summary",
        },
        style: {
            // color: '000000',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "Atlanta",
        id: "atlanta",
        link: "https://www.hulu.com/series/atlanta-3529d0f1-acaf-476d-8be3-66cd6bf12530",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Comedy &#149 Drama &#149 Music &#149 2 Seasons &#149 2016 - Present",
            summary: "Based in Atlanta, Earn and his cousin Alfred try to make their way in the world through the rap scene. Along the way they come face to face with social and economic issues touching on race, relationships, poverty, status, and parenthood.",
        },
        style: {
            color: '584029',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "313999",
            reelgoodLink: "https://reelgood.com/show/atlanta-2016",
            imdbID: "tt4288182",
        },
    },
    {
        name: 'Attack on Titan',
        id: 'attack',
        link: 'https://www.hulu.com/series/attack-on-titan-9c91ffa3-dc20-48bf-8bc5-692e37c76d88',
        info: {
            service: 'hulu',
            // studio: 'studio',
            location: 'Hulu',
            // date: '',
            // weekday: '',
            // desc: {
            // //    seasons: 1,
            // //    yearStart: 2021,
            // //    yearEnd: null,
            // //    genre: [
            // //        'crime',
            // //        'comedy',
            // //    ],
            // },
            // summary: "summary",
        },
        style: {
            // color: '000000',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'The Boys',
        id: 'boys',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            // description: 'Action &#149 Crime &#149 Drama &#149 2 Seasons &#149 2019 - Present',
            // summary: "summary",
        },
        style: {
            color: '660000',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/the-boys-2019',
            imdbID: 'tt1190634',
            subReddit: 'TheBoys',
        },
    },
    {
        name: 'Disenchantment',
        id: 'disenchant',
        link: {
            netflix: '80095697'
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Coming Soon',
            // date: '',
            // weekday: '',
            // desc: {
            //     seasons: 2,
            //     yearStart: 2020,
            //     yearEnd: null,
            //     genre: [
            //         'crime',
            //         'comedy',
            //     ],
            // },
            // summary: "summary",
        },
        style: {
            // color: '000000',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: "The Expanse",
        id: "expanse",
        link: {
            primeVideo: 'B08MMJTJSH',
        },
        info: {
            service: '',
            studio: '',
            location: "Prime Video",
            description: "Action &#149 Adventure &#149 Sci-Fi &#149 6 Seasons &#149 2015 - Present",
            summary: "Hundreds of years in the future, things are different than what we are used to after humans have colonized the solar system and Mars has become an independent military power. Rising tensions between Earth and Mars have put them on the brink of war. Against this backdrop, a hardened detective and a rogue ship's captain come together to investigate the case of a missing young woman. The investigation leads them on a race across the solar system that could expose the greatest conspiracy in human history.",
        },
        style: {
            color: '466A83',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: "280619",
            reelgoodLink: "https://reelgood.com/show/the-expanse-2015",
            imdbID: "tt3230854",
            subReddit: 'TheExpanse',
        },
    },
    {
        name: 'F is for Family',
        id: 'fisforfam',
        link: 'https://www.netflix.com/title/80028732',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            description: 'Animation &#149 Comedy &#149 Drama &#149 4 Seasons &#149 2015 - Present',
            // summary: "summary",
        },
        style: {
            color: '0B6F38',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/f-is-for-family-2015',
            imdbID: 'tt4326894',
            subReddit: null,
        },
    },
    {
        name: 'Falcon and the Winter Soldier',
        id: 'falcon',
        // link: {
        //     netflix: '80197526'
        // },
        info: {
            service: 'disney',
            studio: 'marvel',
            location: 'Disney+',
            // date: '',
            // weekday: '',
            // desc: {
            // //    seasons: 1,
            // //    yearStart: 2021,
            // //    yearEnd: null,
            // //    genre: [
            // //        'crime',
            // //        'comedy',
            // //    ],
            // },
            // summary: "summary",
        },
        style: {
            // color: '000000',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Invincible',
        id: 'invincible',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            // description: 'Action &#149 Animation &#149 Superhero &#149 ___ Seasons &#149 Y000 - Present',
            // summary: "summary",
        },
        style: {
            color: '6C7866',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/invincible-2021',
            // imdbID: 'identifier',
            // subReddit: null,
        },
    },
    {
        name: "It's Always Sunny in Philadelphia",
        id: "always",
        link: "https://www.hulu.com/series/its-always-sunny-in-philadelphia-2171423f-3326-4dfa-b193-b40494e60109",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Comedy &#149 14 Seasons &#149 2005 - Present",
            summary: "Four egocentric friends who run a neighborhood Irish pub in Philadelphia try to find their way through the adult world of work and relationships. Unfortunately, their warped views and precarious judgments often lead them to trouble, creating a myriad of uncomfortable situations that usually only get worse before they get better.",
        },
        style: {
            color: '5c666a',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: "tall",
        },
        apps: {
            tvTimeID: "75805",
            // tvTimeRate: "8.28",
            reelgoodLink: "https://reelgood.com/show/its-always-sunny-in-philadelphia-2005",
            // reelgoodRate: "90",
            imdbID: "tt0472954",
            // imdbRate: "8.8",
            subReddit: "IASIP",
        },
    },
    {
        name: 'Loki',
        id: 'loki',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            description: 'Action & Adventure &#149 Fantasy &#149 1 Season &#149 2021 - Present',
            summary: "Loki, the God of Mischief, steps out of his brother's shadow to embark on an adventure that takes place after the events of Avengers: Endgame.",
        },
        style: {
            color: 'a87643',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: '362472',
            reelgoodLink: 'https://reelgood.com/show/loki-2021',
            imdbID: 'tt9140554',
            // subReddit: null,
        },
    },
    {
        name: 'Manifest',
        id: 'manifest',
        // link: 'watchlink',
        info: {
            service: 'netflix',
            studio: '',
            location: 'Coming Soon',
            description: 'Drama &#149 Mystery &#149 3 Seasons &#149 2018 - Present',
            summary: "A commercial airliner suddenly reappears after being missing for five years. As those aboard reintegrate into society, they experience guiding voices and visions of events yet to occur, and soon a deeper mystery unfolds.",
        },
        style: {
            color: '504A6A',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '349271',
            reelgoodLink: 'https://reelgood.com/show/manifest-2018',
            imdbID: 'tt8421350',
            subReddit: 'ManifestNBC',
        },
    },
    {
        name: 'Mythic Quest',
        id: 'mythic',
        link: null,
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            // description: 'Genre1 &#149 Genre2 &#149 Genre2 &#149 ___ Seasons &#149 Y000 - Y999',
            // summary: "summary",
        },
        style: {
            color: '2F322F',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/mythic-quest-2020',
            // imdbID: 'identifier',
            subReddit: 'MythicQuest',
        },
    },
    {
        name: 'Nine Perfect Strangers',
        id: 'nine',
        link: 'https://www.hulu.com/series/nine-perfect-strangers-2be55e1a-4c31-4af6-aa25-e5c85528b73a',
        info: {
            service: 'hulu',
            studio: 'hulu',
            location: 'Hulu',
            desc: {
                seasons: 1,
                yearStart: 2021,
                yearEnd: null,
                genre: [
                    'drama',
                    'mystery',
                ],
            },
            summary: "Based on The New York Times bestselling book by author Liane Moriarty, “Nine Perfect Strangers” takes place at a boutique health-and-wellness resort that promises healing and transformation as nine stressed city dwellers try to get on a path to a better way of living. Watching over them during this 10-day retreat is the resort's director, Masha, a woman on a mission to reinvigorate their tired minds and bodies. However, these nine “perfect” strangers have no idea what is about to hit them.",
        },
        style: {
            color: '6b7790',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '376815',
            reelgoodLink: 'https://reelgood.com/show/nine-perfect-strangers',
            imdbID: 'tt8760932',
            subReddit: 'nineperfectstrangers',
        },
    },
    {
        name: 'Ozark',
        id: 'ozark',
        link: 'https://www.netflix.com/title/80117552',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            description: 'Crime &#149 Drama &#149 Thriller &#149 3 Seasons &#149 2017 - Present',
            // summary: "summary",
        },
        style: {
            color: '660000',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/ozark-2017',
            imdbID: 'tt5071412',
            subReddit: 'Ozark',
        },
    },
    {
        name: 'Paradise PD',
        id: 'paradise',
        link: {
            netflix: '80191522'
        },
        info: {
            service: 'netflix',
            studio: 'netflix',
            location: 'Netflix',
            // date: '',
            // weekday: '',
            // desc: {
            // //    seasons: 1,
            // //    yearStart: 2021,
            // //    yearEnd: null,
            // //    genre: [
            // //        'crime',
            // //        'comedy',
            // //    ],
            // },
            // summary: "summary",
        },
        style: {
            // color: '000000',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'Peaky Blinders',
        id: 'peaky',
        link: 'https://www.netflix.com/title/80002479',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            description: 'Crime &#149 Drama &#149 5 Seasons &#149 2013 - Present',
            // summary: "summary",
        },
        style: {
            color: '493c35',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/peaky-blinders-2013',
            imdbID: 'tt2442560',
            // subReddit: null,
        },
    },
    {
        name: "Rick and Morty",
        id: "rick",
        link: null,
        info: {
            service: '',
            studio: '',
            location: "Adult Swim",
            description: "Animation &#149 Comedy &#149 5 Seasons &#149 2013 - Present",
            summary: "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty.s already unstable family life, these events cause Morty much distress at home and school.",
        },
        style: {
            color: '2D1D54',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "275274",
            reelgoodLink: "https://reelgood.com/show/rick-and-morty-2013",
            imdbID: "tt2861424",
            subReddit: "rickandmorty",
        },
    },
    {
        name: 'Snowfall',
        id: 'snowfall',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            // description: 'Genre1 &#149 Genre2 &#149 Genre2 &#149 ___ Seasons &#149 Y000 - Y999',
            // summary: "summary",
        },
        style: {
            color: '1A114D',
            posterType: 'jpeg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: null,
        },
    },
    {
        name: 'Snowpiercer',
        id: 'snowpiercer',
        link: null,
        info: {
            service: '',
            studio: '',
            location: 'Coming Soon',
            description: 'Action &#149 Drama &#149 Sci-Fi &#149 2 Seasons &#149 2020 - Present',
            // summary: "summary",
        },
        style: {
            color: '444743',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/snowpiercer-1',
            imdbID: 'tt6156584',
            // subReddit: null,
        },
    },
    {
        name: 'Squid Game',
        id: 'squid',
        link: {
            netflix: '81040344',
        },
        info: {
            service: 'netflix',
            studio: '',
            location: 'Netflix',
            description: 'Action &#149 Adventure &#149 Drama &#149 1 Season &#149 2021 - Present',
            summary: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits - with deadly high stakes.",
        },
        style: {
            color: '3f1513', // 7C4E31
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            tvTimeID: '383275',
            reelgoodLink: 'https://reelgood.com/show/squid-game-2021',
            imdbID: 'tt10919420',
            subReddit: 'squidgame',
        },
    },

]
const movieData8 = [
    {
        name: 'Game of Thrones',
        id: 'gameofthrones',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'HBO Max',
            description: 'Action &#149 Adventure &#149 Fantasy &#149 8 Seasons &#149 2011 - 2019',
            summary: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
        },
        style: {
            color: '4e3e46',
            posterType: 'jpg',
            titleType: 'svg',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            // reelgoodLink: 'link',
            imdbID: 'tt0944947',
            // subReddit: null,
        },
    },
    {
        name: 'How I Met Your Mother',
        id: 'himym',
        link: 'https://www.hulu.com/series/how-i-met-your-mother-bc68ac79-3ace-4427-9ec0-5ee6f314d194',
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            // description: 'Comedy &#149 Romance &#149 9 Seasons &#149 2005 - 2014',
            // summary: "summary",
        },
        style: {
            color: 'C7A533',
            posterType: 'webp',
            titleType: 'svg',
            titleSize: 'tall',
        },
        apps: {
            tvTimeID: '75760',
            reelgoodLink: 'https://reelgood.com/show/how-i-met-your-mother-2005',
            imdbID: 'tt0460649',
            subReddit: 'HIMYM',
        },
    },
    {
        name: "Lost",
        id: "lost",
        link: "https://www.hulu.com/series/lost-466b3994-b574-44f1-88bc-63707507a6cb",
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            description: "Action &#149 Adventure &#149 6 Seasons &#149 2004 - 2010",
            summary: "The survivors of a plane crash find themselves stranded on a mysterious island. They are forced to work together for their survival when they realise that they are not alone on the island.",
        },
        style: {
            color: '6a5828',
            posterType: 'webp',
            titleType: 'png',
            titleSize: "wide",
        },
        apps: {
            tvTimeID: "73739",
            reelgoodLink: "https://reelgood.com/show/lost-2004",
            imdbID: "tt0411008",
        },
    },
    {
        name: 'New Girl',
        id: 'newgirl',
        link: {
            netflix: '70196145',
        },
        info: {
            service: 'netflix',
            studio: '',
            location: 'Netflix',
            // description: 'Genre1 &#149 Genre2 &#149 Genre2 &#149 ___ Seasons &#149 Y000 - Present',
            // summary: "summary",
        },
        style: {
            color: 'a59c4f',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: null,
        },
    },
    {
        name: 'The Office',
        id: 'office',
        link: 'https://www.peacocktv.com/watch/asset/tv/the-office/4902514835143843112',
        info: {
            service: '',
            studio: '',
            location: 'Peacock',
            // description: 'Genre1 &#149 Genre2 &#149 Genre2 &#149 ___ Seasons &#149 Y000 - Present',
            // summary: "summary",
        },
        style: {
            color: '7E6C64',
            posterType: 'jpg',
            titleType: 'svg',
            titleSize: 'wide',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/show/the-office-2005',
            // imdbID: 'identifier',
            // subReddit: null,
        },
    },
]
const movieDataArchive = [
    {
        name: 'Fargo',
        id: 'fargo',
        link: 'https://www.hulu.com/series/fargo-203cda1b-7919-40fb-ab36-1e45b3ed2a50',
        info: {
            service: 'hulu',
            studio: '',
            location: 'Hulu',
            // description: 'Genre1 &#149 Genre2 &#149 Genre2 &#149 ___ Seasons &#149 Y000 - Present',
            // summary: "summary",
        },
        style: {
            color: '28374E',
            // posterType: 'webp',
            // titleType: 'png',
            // titleSize: 'wide',
        },
        apps: {
            // tvTimeID: 'identifier',
            // reelgoodLink: 'link',
            // imdbID: 'identifier',
            // subReddit: 'subreddit',
        },
    },
    {
        name: 'This is the End',
        id: 'theend',
        // link: 'watchlink',
        info: {
            service: '',
            studio: '',
            location: 'Starz',
            description: 'Comedy &#149 2013',
            summary: "Six Los Angeles celebrities are stuck in James Franco's house after a series of devastating events just destroyed the city. Inside, the group not only have to face the apocalypse, but themselves.",
        },
        style: {
            color: '3b2420',
            posterType: 'webp',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            // tvTimeID: null,
            reelgoodLink: 'https://reelgood.com/movie/this-is-the-end-2013',
            imdbID: 'tt1245492',
            // subReddit: null,
        },
    },
    {
        name: "Shang-Chi",
        id: "shang",
        link: null,
        info: {
            service: '',
            studio: '',
            location: "Disney+",
            description: "Action &#149 Adventure &#149 Fantasy &#149 2021",
            summary: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
        },
        style: {
            color: '4b3831',
            posterType: 'jpg',
            titleType: 'png',
            titleSize: 'mid',
        },
        apps: {
            tvTimeID: null,
            reelgoodLink: "https://reelgood.com/movie/shangchi-and-the-legend-of-the-ten-rings-2021",
            imdbID: 'tt9376612',
        },
    },
]

const movieData = [
    movieData0,
    movieData1,
    movieData2,
    movieData3,
    movieData4,
    movieData5,
    movieData6,
    movieData7,
    movieData8,
]