const thumbData = {
    'tv': 'tv.png',
    'user': 'account.png',
    'globe': 'globe.png',
    'more': 'plus.png',
    'atom': 'molecule.png',
    'work': 'work.png',
    'diamond': 'diamond.png',
    'course': 'course.png',
    'book': 'book.png',
    'plane': 'plane.png',
    'folder': 'folder.png',
    'check': 'check.png',
    'note': 'note.png',
    'pod': 'podcasts.png',
    'svg': 'svg.png',
    'finance': 'finance.png',
    'calculus': 'calculus.png',
    'gym': 'gym.png',
    'indorg': 'indorg.png',
    'money': 'money.png',
    'thought': 'thought.png',

    // brands
    'iberia': 'iberia.jpeg',
    'british': 'ba.jpeg',
    'ryanair': 'ryanair.jpeg',
    'reddit': 'reddit.jpeg',
    hp: 'hp.svg',

    // flags
    'hk': 'hk.png',
    'usa': 'usa.png',
    'uk': 'uk.png',
    'india': 'india.png',
    'australia': 'australia.png',
    'sa': 'sa.png',
    'zim': 'zim.png',
    'canada': 'canada.png',
    'spain': 'spain.png',
}